### ISSUE TITLE
using default: :now dumps 

### ISSUE THREAD

**Issue by sachinsiby** [SchemaPlus/schema_plus_default_expr#1]
I have the following code in a migration:

`add_column :companies, :synced_at, :datetime, default: :now`

after I run a `rake db:migrate`, I get the following in my `schema.rb` file:

`t.datetime "synced_at",  default: { expr: "now()" }, default: "now()"`

Note that there are now two `default:` keys. In this case, the second one takes precedence, which means that the first and intended `default` will be ignored.

The Dumper needs to only output the `default: { expr: "now()" }` option key.

**Comment by ronen** [comment]
@sachinsiby thanks for the bug report.  I've released v0.1.1 with this bug fixed.
